In [1]:
from tensorflow.keras.preprocessing.text import one_hot


In [2]:
sent =[ 'the glass of milk',
        'the glass of juice',
        'the cup of tea',
        'I am good boy',
        'I am a good developer',
        'understand the meaning of words',
        'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
voc_size = 10000

In [6]:

one_hot_repr = [one_hot(words, voc_size) for words in sent]
one_hot_repr

[[9409, 6336, 4594, 8707],
 [9409, 6336, 4594, 7207],
 [9409, 6954, 4594, 9782],
 [6100, 5246, 8188, 6739],
 [6100, 5246, 4367, 8188, 2503],
 [3865, 9409, 340, 4594, 9663],
 [1525, 3772, 2067, 8188]]

In [7]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.models import Sequential
from tensorflow.keras.utils import pad_sequences


In [8]:
import numpy as np

In [9]:
set_length = 8
embedded_docs = pad_sequences(one_hot_repr, maxlen=set_length, padding='pre')
embedded_docs

array([[   0,    0,    0,    0, 9409, 6336, 4594, 8707],
       [   0,    0,    0,    0, 9409, 6336, 4594, 7207],
       [   0,    0,    0,    0, 9409, 6954, 4594, 9782],
       [   0,    0,    0,    0, 6100, 5246, 8188, 6739],
       [   0,    0,    0, 6100, 5246, 4367, 8188, 2503],
       [   0,    0,    0, 3865, 9409,  340, 4594, 9663],
       [   0,    0,    0,    0, 1525, 3772, 2067, 8188]])

In [10]:
dim=10

In [11]:
model = Sequential()
model.add(Embedding(voc_size, dim, input_length=set_length))
model.compile('adam', 'mse')

In [12]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [13]:
embedded_docs[0]

array([   0,    0,    0,    0, 9409, 6336, 4594, 8707])

In [14]:
model.predict(embedded_docs[0])

1/1 [==============================] - 1s 1s/step


array([[ 0.01755892,  0.02276037, -0.03727264, -0.00792072, -0.03235445,
         0.04243684, -0.02954094,  0.00750558,  0.0049943 ,  0.00347584],
       [ 0.01755892,  0.02276037, -0.03727264, -0.00792072, -0.03235445,
         0.04243684, -0.02954094,  0.00750558,  0.0049943 ,  0.00347584],
       [ 0.01755892,  0.02276037, -0.03727264, -0.00792072, -0.03235445,
         0.04243684, -0.02954094,  0.00750558,  0.0049943 ,  0.00347584],
       [ 0.01755892,  0.02276037, -0.03727264, -0.00792072, -0.03235445,
         0.04243684, -0.02954094,  0.00750558,  0.0049943 ,  0.00347584],
       [-0.02107589,  0.04893339,  0.01311762,  0.04654893,  0.00831459,
        -0.04782008,  0.01490602, -0.04824158,  0.00357075, -0.03937368],
       [-0.00300447, -0.00878084, -0.01930522,  0.02803368, -0.00632124,
        -0.02274015, -0.0481748 ,  0.03628751,  0.00228709, -0.02180822],
       [-0.01124537,  0.04676299, -0.02994161, -0.00613667,  0.02443634,
        -0.01687586, -0.00896763,  0.01396443